// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qyzvrridbeljlpmzpzmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5enZycmlkYmVsamxwbXpwem1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MDg2MTUsImV4cCI6MjA3NzQ4NDYxNX0.dlMNg1KzrjRAUhC5e-eEK5hqsLok_MIVDeNqX_dnFBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);